# Generated by Django 5.0.3 on 2026-04-10 18:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Categoria CSC',
                'verbose_name_plural': 'Categorias CSC',
                'db_table': 'categoria_CSC',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=70, null=True)),
                ('codigo_ibge', models.CharField(db_index=True, max_length=20, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Norm',
            fields=[
                ('id_norma', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100, unique=True)),
                ('Direcionamento', models.URLField()),
            ],
            options={
                'db_table': 'norma',
                'ordering': ['Nome'],
            },
        ),
        migrations.CreateModel(
            name='NormISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_norma', models.CharField(db_index=True, max_length=30)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'norma_iso',
                'ordering': ['codigo_norma'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id_plataforma', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100, unique=True)),
                ('Direcionamento', models.URLField()),
            ],
            options={
                'db_table': 'plataforma',
                'ordering': ['Nome'],
            },
        ),
        migrations.CreateModel(
            name='YearReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(db_index=True, unique=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'ano_referencia',
                'ordering': ['ano'],
            },
        ),
        migrations.CreateModel(
            name='FutureIndicatorCSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_indicador', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('opcoes_predefinidas', models.JSONField(blank=True, null=True)),
                ('ods', models.CharField(max_length=10)),
                ('unidade_medida', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(db_column='FK_categoria_CSC_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.categoriacsc')),
                ('ano_referencia', models.ForeignKey(db_column='FK_ano_referencia_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.yearreference')),
            ],
            options={
                'verbose_name': 'Indicador Futuro CSC',
                'verbose_name_plural': 'Indicadores Futuros CSC',
                'db_table': 'indicador_futuro_CSC',
            },
        ),
        migrations.CreateModel(
            name='FutureIndicatorValueCSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('fonte', models.CharField(blank=True, max_length=500, null=True)),
                ('indicador_futuro', models.ForeignKey(db_column='FK_indicador_futuro_CSC_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.futureindicatorcsc')),
                ('municipio', models.ForeignKey(db_column='FK_municipio_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.municipality')),
            ],
            options={
                'verbose_name': 'Levantamento Futuro CSC',
                'verbose_name_plural': 'Levantamentos Futuros CSC',
                'db_table': 'levantamento_futuro_CSC',
            },
        ),
        migrations.CreateModel(
            name='EvidencePDFCSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('caminho_arquivo', models.CharField(max_length=500)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('levantamento_futuro', models.ForeignKey(db_column='FK_levantamento_futuro_CSC_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.futureindicatorvaluecsc')),
            ],
            options={
                'verbose_name': 'Evidência PDF CSC',
                'verbose_name_plural': 'Evidências PDF CSC',
                'db_table': 'evidencia_pdf_CSC',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('apoio', 'Apoio'), ('perfil', 'Perfil')], db_index=True, max_length=20)),
                ('ods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('unidade_medida', models.CharField(blank=True, max_length=100, null=True)),
                ('opcoes_predefinidas', models.JSONField(blank=True, null=True)),
                ('categoria', models.ForeignKey(db_column='FK_categoria_id', on_delete=django.db.models.deletion.PROTECT, to='accounts.category')),
            ],
            options={
                'db_table': 'indicador',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorValueYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('fonte', models.CharField(blank=True, max_length=255, null=True)),
                ('indicador', models.ForeignKey(db_column='FK_indicador_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.indicator')),
                ('municipio', models.ForeignKey(db_column='FK_municipio_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.municipality')),
            ],
            options={
                'db_table': 'valor_indicador_ano',
            },
        ),
        migrations.CreateModel(
            name='EvidencePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('caminho_arquivo', models.CharField(max_length=500)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('valor_indicador_ano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.indicatorvalueyear')),
            ],
            options={
                'db_table': 'evidencia_pdf_iso',
            },
        ),
        migrations.CreateModel(
            name='ISO37120Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('nome_indicador', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('core', 'Principal'), ('supporting', 'Apoio'), ('profile', 'Perfil')], max_length=20)),
                ('ods', models.CharField(max_length=10)),
                ('unidade', models.CharField(max_length=50)),
                ('dado_2022', models.CharField(blank=True, max_length=100, null=True)),
                ('dado_2023', models.CharField(blank=True, max_length=100, null=True)),
                ('dado_2024', models.CharField(blank=True, max_length=100, null=True)),
                ('dado_2025', models.CharField(blank=True, max_length=100, null=True)),
                ('fonte_2022', models.CharField(blank=True, max_length=500, null=True)),
                ('fonte_2023', models.CharField(blank=True, max_length=500, null=True)),
                ('fonte_2024', models.CharField(blank=True, max_length=500, null=True)),
                ('fonte_2025', models.CharField(blank=True, max_length=500, null=True)),
                ('anexo_2022', models.FileField(blank=True, null=True, upload_to='iso37120/anexos/')),
                ('anexo_2023', models.FileField(blank=True, null=True, upload_to='iso37120/anexos/')),
                ('anexo_2024', models.FileField(blank=True, null=True, upload_to='iso37120/anexos/')),
                ('anexo_2025', models.FileField(blank=True, null=True, upload_to='iso37120/anexos/')),
                ('cidade', models.CharField(default='Londrina', max_length=100)),
                ('estado', models.CharField(default='PR', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'iso37120_indicators',
                'ordering': ['categoria', 'nome_indicador'],
                'unique_together': {('nome_indicador', 'cidade', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='ISO37122Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('nome_indicador', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('core', 'Principal'), ('supporting', 'Apoio'), ('profile', 'Perfil')], max_length=20)),
                ('ods', models.CharField(max_length=10)),
                ('unidade', models.CharField(max_length=50)),
                ('dado_2022', models.CharField(blank=True, max_length=100, null=True)),
                ('dado_2023', models.CharField(blank=True, max_length=100, null=True)),
                ('dado_2024', models.CharField(blank=True, max_length=100, null=True)),
                ('dado_2025', models.CharField(blank=True, max_length=100, null=True)),
                ('fonte_2022', models.CharField(blank=True, max_length=500, null=True)),
                ('fonte_2023', models.CharField(blank=True, max_length=500, null=True)),
                ('fonte_2024', models.CharField(blank=True, max_length=500, null=True)),
                ('fonte_2025', models.CharField(blank=True, max_length=500, null=True)),
                ('anexo_2022', models.FileField(blank=True, null=True, upload_to='iso37122/anexos/')),
                ('anexo_2023', models.FileField(blank=True, null=True, upload_to='iso37122/anexos/')),
                ('anexo_2024', models.FileField(blank=True, null=True, upload_to='iso37122/anexos/')),
                ('anexo_2025', models.FileField(blank=True, null=True, upload_to='iso37122/anexos/')),
                ('cidade', models.CharField(default='Londrina', max_length=100)),
                ('estado', models.CharField(default='PR', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'iso37122_indicators',
                'ordering': ['categoria', 'nome_indicador'],
                'unique_together': {('nome_indicador', 'cidade', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='ISO37123Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('nome_indicador', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('core', 'Principal'), ('supporting', 'Apoio'), ('profile', 'Perfil')], max_length=20)),
                ('ods', models.CharField(max_length=10)),
                ('unidade', models.CharField(max_length=50)),
                ('dado_2022', models.CharField(blank=True, max_length=100, null=True)),
                ('dado_2023', models.CharField(blank=True, max_length=100, null=True)),
                ('dado_2024', models.CharField(blank=True, max_length=100, null=True)),
                ('dado_2025', models.CharField(blank=True, max_length=100, null=True)),
                ('fonte_2022', models.CharField(blank=True, max_length=500, null=True)),
                ('fonte_2023', models.CharField(blank=True, max_length=500, null=True)),
                ('fonte_2024', models.CharField(blank=True, max_length=500, null=True)),
                ('fonte_2025', models.CharField(blank=True, max_length=500, null=True)),
                ('anexo_2022', models.FileField(blank=True, null=True, upload_to='iso37123/anexos/')),
                ('anexo_2023', models.FileField(blank=True, null=True, upload_to='iso37123/anexos/')),
                ('anexo_2024', models.FileField(blank=True, null=True, upload_to='iso37123/anexos/')),
                ('anexo_2025', models.FileField(blank=True, null=True, upload_to='iso37123/anexos/')),
                ('cidade', models.CharField(default='Londrina', max_length=100)),
                ('estado', models.CharField(default='PR', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'iso37123_indicators',
                'ordering': ['categoria', 'nome_indicador'],
                'unique_together': {('nome_indicador', 'cidade', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='ISO37125Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('nome_indicador', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('core', 'Principal'), ('supporting', 'Apoio'), ('profile', 'Perfil')], max_length=20)),
                ('ods', models.CharField(max_length=10)),
                ('unidade', models.CharField(max_length=50)),
                ('dado_2022', models.CharField(blank=True, max_length=100, null=True)),
                ('dado_2023', models.CharField(blank=True, max_length=100, null=True)),
                ('dado_2024', models.CharField(blank=True, max_length=100, null=True)),
                ('dado_2025', models.CharField(blank=True, max_length=100, null=True)),
                ('fonte_2022', models.CharField(blank=True, max_length=500, null=True)),
                ('fonte_2023', models.CharField(blank=True, max_length=500, null=True)),
                ('fonte_2024', models.CharField(blank=True, max_length=500, null=True)),
                ('fonte_2025', models.CharField(blank=True, max_length=500, null=True)),
                ('anexo_2022', models.FileField(blank=True, null=True, upload_to='iso37125/anexos/')),
                ('anexo_2023', models.FileField(blank=True, null=True, upload_to='iso37125/anexos/')),
                ('anexo_2024', models.FileField(blank=True, null=True, upload_to='iso37125/anexos/')),
                ('anexo_2025', models.FileField(blank=True, null=True, upload_to='iso37125/anexos/')),
                ('cidade', models.CharField(default='Londrina', max_length=100)),
                ('estado', models.CharField(default='PR', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'iso37125_indicators',
                'ordering': ['categoria', 'nome_indicador'],
                'unique_together': {('nome_indicador', 'cidade', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='ExternalAPIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_api', models.CharField(max_length=100)),
                ('tipo_dado', models.CharField(max_length=100)),
                ('dados_json', models.JSONField()),
                ('data_coleta', models.DateTimeField()),
                ('valido_ate', models.DateTimeField()),
                ('municipio', models.ForeignKey(db_column='municipio_id', on_delete=django.db.models.deletion.CASCADE, related_name='external_data', to='accounts.municipality')),
            ],
            options={
                'verbose_name': 'Dado Externo de API',
                'verbose_name_plural': 'Dados Externos de APIs',
                'db_table': 'dados_externos_api',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('categoria', models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Gestor'), ('COMMON', 'Usuário')], db_index=True, max_length=10, null=True)),
                ('user_type', models.CharField(choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Gestor'), ('COMMON', 'Usuário Comum')], db_index=True, default='COMMON', max_length=10)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('senha_temporaria_ativa', models.BooleanField(db_index=True, default=True)),
                ('token_recuperacao', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('data_token_recuperacao', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
                ('municipio', models.ForeignKey(blank=True, db_column='FK_municipio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='accounts.municipality')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalityRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao_total_categoria', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('indicadores_preenchidos', models.PositiveIntegerField(default=0)),
                ('indicadores_totais', models.PositiveIntegerField(default=0)),
                ('cor_classificacao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_calculo', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='accounts.category')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='accounts.municipality')),
            ],
            options={
                'db_table': 'ranking_municipios',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=100)),
                ('requisitos', models.JSONField(blank=True, null=True)),
                ('FK_norma_iso', models.ForeignKey(db_column='FK_norma_iso_id', on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='accounts.normiso')),
            ],
            options={
                'verbose_name': 'Certificação',
                'verbose_name_plural': 'Certificações',
                'db_table': 'certificacao',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='norma_iso',
            field=models.ForeignKey(db_column='FK_norma_iso_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.normiso'),
        ),
        migrations.AddField(
            model_name='normiso',
            name='ano_referencia',
            field=models.ForeignKey(db_column='FK_ano_referencia_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.yearreference'),
        ),
    ]
