# Generated by Django 5.0.3 on 2026-05-04 00:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('apoio', 'Apoio'), ('perfil', 'Perfil')], db_index=True, max_length=20)),
                ('opcoes_predefinidas', models.JSONField(blank=True, null=True)),
                ('unidade_medida', models.CharField(blank=True, max_length=100, null=True)),
                ('direcao_melhoria', models.IntegerField(blank=True, null=True)),
                ('ods', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'db_table': 'indicador',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('estado', models.CharField(blank=True, max_length=70, null=True)),
                ('subdivision_id', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('codigo_ibge', models.CharField(db_index=True, max_length=20, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('regiao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Região')),
                ('porte', models.CharField(blank=True, max_length=50, null=True, verbose_name='Porte da Cidade')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='NormISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_norma', models.CharField(db_index=True, max_length=30)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'norma_iso',
                'ordering': ['codigo_norma'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
                'db_table': 'plataforma',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='YearReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(db_index=True, unique=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'ano_referencia',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(db_column='FK_categoria_id', on_delete=django.db.models.deletion.CASCADE, related_name='categoria_indicadores', to='accounts.category')),
                ('indicador', models.ForeignKey(db_column='FK_indicador_id', on_delete=django.db.models.deletion.CASCADE, related_name='indicador_categorias', to='accounts.indicator')),
            ],
            options={
                'verbose_name': 'Indicador Categoria',
                'verbose_name_plural': 'Indicadores Categorias',
                'db_table': 'indicador_categoria',
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='indicadores', through='accounts.IndicatorCategory', to='accounts.category'),
        ),
        migrations.CreateModel(
            name='IndicatorValueYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numerico', models.IntegerField(blank=True, null=True)),
                ('valor_texto', models.CharField(blank=True, max_length=255, null=True)),
                ('fonte', models.CharField(blank=True, max_length=255, null=True)),
                ('indicador', models.ForeignKey(db_column='FK_indicador_id', on_delete=django.db.models.deletion.CASCADE, related_name='valores_ano', to='accounts.indicator')),
                ('municipio', models.ForeignKey(db_column='FK_municipio_id', on_delete=django.db.models.deletion.CASCADE, related_name='valores_indicadores', to='accounts.municipality')),
            ],
            options={
                'verbose_name': 'Valor do Indicador por Ano',
                'verbose_name_plural': 'Valores dos Indicadores por Ano',
                'db_table': 'valor_indicador_ano',
            },
        ),
        migrations.CreateModel(
            name='EvidencePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('caminho_arquivo', models.CharField(max_length=500)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('valor_indicador_ano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.indicatorvalueyear')),
            ],
            options={
                'db_table': 'evidencia_pdf_iso',
            },
        ),
        migrations.CreateModel(
            name='ExternalAPIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_api', models.CharField(max_length=100)),
                ('tipo_dado', models.CharField(max_length=100)),
                ('dados_json', models.JSONField()),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('valido_ate', models.DateTimeField(blank=True, null=True)),
                ('municipio', models.ForeignKey(db_column='FK_municipio_id', on_delete=django.db.models.deletion.CASCADE, related_name='dados_externos_api', to='accounts.municipality')),
            ],
            options={
                'verbose_name': 'Dado Externo API',
                'verbose_name_plural': 'Dados Externos API',
                'db_table': 'dados_externos_api',
                'ordering': ['-data_coleta'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('categoria', models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Gestor'), ('COMMON', 'Usuário')], db_index=True, max_length=10, null=True)),
                ('user_type', models.CharField(choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Gestor'), ('COMMON', 'Usuário Comum')], db_index=True, default='COMMON', max_length=10)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('senha_temporaria_ativa', models.BooleanField(db_index=True, default=True)),
                ('token_recuperacao', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('data_token_recuperacao', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
                ('municipio', models.ForeignKey(blank=True, db_column='FK_municipio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='accounts.municipality')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalityRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao_total_categoria', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('indicadores_preenchidos', models.PositiveIntegerField(default=0)),
                ('indicadores_totais', models.PositiveIntegerField(default=0)),
                ('cor_classificacao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_calculo', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='accounts.category')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='accounts.municipality')),
            ],
            options={
                'verbose_name': 'Ranking de Município',
                'verbose_name_plural': 'Rankings de Municípios',
                'db_table': 'ranking_municipios',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=100)),
                ('requisitos', models.JSONField(blank=True, null=True)),
                ('norma_iso', models.ForeignKey(db_column='FK_norma_iso_id', on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='accounts.normiso')),
            ],
            options={
                'verbose_name': 'Certificação',
                'verbose_name_plural': 'Certificações',
                'db_table': 'certificacao',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='norma_iso',
            field=models.ForeignKey(db_column='FK_norma_iso_id', on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='accounts.normiso'),
        ),
        migrations.AddField(
            model_name='category',
            name='plataforma',
            field=models.ForeignKey(db_column='FK_plataforma_id', on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='accounts.platform'),
        ),
        migrations.AddField(
            model_name='platform',
            name='ano_referencia',
            field=models.ForeignKey(db_column='FK_ano_referencia_id', on_delete=django.db.models.deletion.CASCADE, related_name='plataformas', to='accounts.yearreference'),
        ),
        migrations.AddField(
            model_name='normiso',
            name='ano_referencia',
            field=models.ForeignKey(db_column='FK_ano_referencia_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.yearreference'),
        ),
        migrations.AddConstraint(
            model_name='indicatorcategory',
            constraint=models.UniqueConstraint(fields=('indicador', 'categoria'), name='uniq_indicador_categoria'),
        ),
        migrations.AddIndex(
            model_name='indicatorvalueyear',
            index=models.Index(fields=['municipio', 'indicador'], name='valor_indic_FK_muni_970770_idx'),
        ),
        migrations.AddIndex(
            model_name='municipalityranking',
            index=models.Index(fields=['municipio', 'categoria'], name='ranking_mun_municip_4e7d4f_idx'),
        ),
    ]
