# Generated by Django 5.0.3 on 2026-05-04 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='norma_iso',
            field=models.ForeignKey(blank=True, db_column='FK_norma_iso_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='accounts.normiso'),
        ),
        migrations.AlterField(
            model_name='category',
            name='plataforma',
            field=models.ForeignKey(blank=True, db_column='FK_plataforma_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='accounts.platform'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('norma_iso__isnull', False), ('plataforma__isnull', False), _connector='OR'), name='categoria_tem_norma_ou_plataforma'),
        ),
    ]
