# Generated by Django 5.0.3 on 2026-04-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='FK_norma_iso',
            new_name='norma_iso',
        ),
    ]
