# Generated by Django 5.0.3 on 2026-05-09 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_category_norma_iso_alter_category_plataforma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingISOCategoriaView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio_id', models.BigIntegerField()),
                ('municipio', models.CharField(max_length=150)),
                ('uf', models.CharField(max_length=70)),
                ('ano', models.PositiveIntegerField()),
                ('norma_id', models.BigIntegerField()),
                ('codigo_norma', models.CharField(max_length=30)),
                ('categoria_id', models.BigIntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('pontuacao_categoria', models.DecimalField(decimal_places=4, max_digits=14)),
                ('indicadores_preenchidos', models.PositiveIntegerField()),
                ('indicadores_totais', models.PositiveIntegerField()),
                ('cor_classificacao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_calculo', models.DateTimeField()),
            ],
            options={
                'db_table': 'vw_ranking_iso_categoria',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='evidencepdf',
            name='apagado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='evidencepdf',
            name='apagado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencepdf',
            name='apagado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_apagadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='deletado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='indicator',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores_deletados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicatorvalueyear',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='indicatorvalueyear',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valores_indicadores_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('ANEXO_APAGADO', 'Anexo apagado'), ('VALOR_ALTERADO', 'Valor alterado'), ('INDICADOR_EDITADO', 'Indicador editado'), ('INDICADOR_DELETADO', 'Indicador deletado'), ('RECUPERACAO', 'Recuperação')], max_length=50)),
                ('objeto_tipo', models.CharField(max_length=100)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('recuperavel', models.BooleanField(default=False)),
                ('recuperado', models.BooleanField(default=False)),
                ('recuperado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('recuperado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria_recuperados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
