# Generated by Django 5.0.3 on 2026-04-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_fk_norma_iso_certification_norma_iso'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='direcao_melhoria',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
