# Generated by Django 5.0.3 on 2026-05-09 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rankingisocategoriaview_evidencepdf_apagado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignacaoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrigatorio', models.BooleanField(default=True)),
                ('preenchido', models.BooleanField(default=False)),
                ('preenchido_em', models.DateTimeField(blank=True, null=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_designacao', to='accounts.indicator')),
                ('preenchido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores_designados_preenchidos', to=settings.AUTH_USER_MODEL)),
                ('valor_indicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_designacao', to='accounts.indicatorvalueyear')),
            ],
            options={
                'db_table': 'designacao_indicador',
            },
        ),
        migrations.CreateModel(
            name='DesignacaoPreenchimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDENTE', max_length=20)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('gestor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('indicadores', models.ManyToManyField(related_name='designacoes_preenchimento', through='accounts.DesignacaoIndicador', to='accounts.indicator')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designacoes_preenchimento', to='accounts.municipality')),
            ],
            options={
                'db_table': 'designacao_preenchimento',
                'ordering': ['-criado_em'],
                'permissions': [('acesso_total_designacao', 'Pode gerenciar todas as designações de preenchimento')],
            },
        ),
        migrations.AddField(
            model_name='designacaoindicador',
            name='designacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='accounts.designacaopreenchimento'),
        ),
        migrations.AddConstraint(
            model_name='designacaoindicador',
            constraint=models.UniqueConstraint(fields=('designacao', 'indicador'), name='uniq_designacao_indicador'),
        ),
    ]
