# Generated by ChatGPT for indicator reference values
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_platformgoalreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='valor_referencia_minimo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='valor_referencia_maximo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='fonte_valor_referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
