# Generated by ChatGPT for decimal indicator values
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_indicator_reference_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorvalueyear',
            name='valor_numerico',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
